modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/legosteenjaap/HorseInBoat/issues"
license = "LGPL-3.0 License"

[[mods]]
modId = "horseinboat"
version = "${version}"
displayName = "HorseInBoat"
authors = "Legosteenjaap"
description = '''
Simple Minecraft mod that makes it easy to put horses in boats.
'''
logoFile = "icon.png"

[[mixins]]
config = "horseinboat.mixins.json"

[[dependencies.horseinboat]]
modId = "neoforge"
type = "required"
versionRange = "[20.4 ,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.horseinboat]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4]"
ordering = "NONE"
side = "BOTH"