name: upload_version_fabric

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21
  JAVA_VERSION: 21
  VERSION: 1.1.6
  RELEASE_NAME: 1.1.6-fabric
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:
          curseforge-id: 576601
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: jZ1T46Hr
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          files: |
            fabric/build/libs/!(*-sources|*-dev-shadow).jar
      - name: Publish (Github)
        uses: Kir-Antipov/mc-publish@v3.3                                   #The specified MC-Publish GitHub Action in the version 3.2
        with:

          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          github-commitish: "1.21"

          name: "$v{{env.VERSION}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|sources|javadoc).jar